---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars:
    username: chrys
    pkg_name: httpd
  tasks:
    - name: Creating new user
      user:
        name: "{{ username }}"
        comment: chrys bimokono
        shell: /bin/bash
          #when: ansible_os_family == "Debian"
    - name: Create file name
      file:
        path: /tmp/ansiblr.txt
        state: touch
        mode: '0600'
    - name: Create directory
      file:
        path: /tmp/dir
        state: directory
        mode: '0755'
    - name: install apache
      yum:
        name: "{{ pkg_name }}"
        state: present

    - name: install finger
      package:
           name: finger
           state: present  

