---
- hosts: qaserver
  become: yes
  ignore_errors: yes
  tasks:
    - name: install packages
      package:
         name: "{{ item }}"
         state: present
      loop:
      - unzip
      - wget
      - httpd


    - name: Download and extract application files
      get_url:
        url: "https://github.com/utrains/static-resume/archive/refs/heads/main.zip"
        dest: "/tmp/main.zip"
      become: true

    - name: Extract files from compressed
      unarchive:
        src: "/tmp/main.zip"
        dest: "/tmp"
        remote_src: true
      become: true

    - name: Copy application files to web server directory
      copy:
        src: "/tmp/static-resume-main/iPortfolio/"
        dest: "/var/www/html/"
        remote_src: true
      become: true

    - name: starting the apache service
      service:
        name: httpd
        state: started
        enabled: true
      become: True    
           
    - name: Check if application is up
      wait_for:
        host: 44.201.19.223
        port: 80
        state: started
      become: true
