---
- hosts: qaserver
  become: yes
  ignore_errors: yes
  tasks:
    - name: install packages
      package:
         name: "{{ item }}"
         state: present
      loop:
      - unzip
      - wget
      - httpd

<<<<<<< HEAD
    - name: download
      shell: wget https://github.com/utrains/static-resume/archive/refs/heads/main.zip
      args:
        executable: /bin/bash
      become: True
=======
    - name: Download and extract application files using get url
      get_url:
        url: "https://github.com/utrains/static-resume/archive/refs/heads/main.zip"
        dest: "/tmp/main.zip"
      become: true
>>>>>>> 2c63e75 (updating my new web yml file)

    - name: extract web files
      command: "unzip main.zip -d /tmp"
      become: True

    - name: copy website files to web server directory
      command: "cp -r /tmp/static-resume-main/iPortfolio/* /var/www/html/"
      become: True

    - name: starting the apache service
      service:
        name: httpd
        state: started
        enabled: true
      become: True    
           
    - name: Pause for web server to start
      pause:
        seconds: 10

    - name: Check if website is accessible
      uri:
        url: "http://localhost/"
        return_content: yes
      register: response

  
  
